### ISSUE TITLE
New packages: monero-gui, feather

### ISSUE THREAD

**Issue by telans** [gentoo-monero/gentoo-monero#8]
**_feather:_**

https://git.wownero.com/feather/feather
https://featherwallet.org/

States that it requires `monero` + `Qt 5.15.0, libqrencode, openpgp`

_**monero-gui:**_

https://github.com/monero-project/monero-gui

Unsure of deps, probably the same

**Comment by 00-matt** [comment]
I'm currently working on packaging up feather :)

**Comment by telans** [comment]
Want a hand?

**Comment by 00-matt** [comment]
I've pushed up a live ebuild (there are no tagged releases yet), some help testing would be great :)

**Comment by telans** [comment]
Looks great, thanks

Do you have connectivity within the wallet? For me the balance synchronises yet there is no other connectivity (fiat equivalent or news feed).
![Screenshot from 2020-10-17 22-05-13](https://user-images.githubusercontent.com/45819748/96333193-efef3d80-10c4-11eb-9141-12a315a30ea8.png)
![Screenshot from 2020-10-17 22-05-32](https://user-images.githubusercontent.com/45819748/96333194-f1206a80-10c4-11eb-9e09-d7690d3167b1.png)

This is strange seeing as tor is not being built. Is this the same for you?

I'll note that GCC segfaults when compiling with `-fipa-pta` but that's an issue for GentooLTO

**Comment by 00-matt** [comment]
Ah, I already had Tor running locally so everything worked for me. I thought that it was optional :(

For now we can add a message after installation explaining that you need to have Tor installed and running. Maybe later on upstream can add a message saying that it failed to connect to the Tor SOCKS server, instead of just silently breaking.

**Comment by telans** [comment]
> For now we can add a message after installation explaining that you need to have Tor installed

A dependency requirement would probably be better for now

**Comment by telans** [comment]
```
- Embedding executables require passing definition to CMake, e.g:
  - `-DTOR=/path/to/tor`
  - `-DXMRIG=/path/to/xmrig`
```
From https://git.wownero.com/feather/feather/commit/aee60f33b7419ebd91fe098e2afcd2d67ef7dfab

I suppose these could be behind a the same USE flags for tor/xmr and solves the need for a locally running tor node?

**Comment by 00-matt** [comment]
I think that this would embed it into the executable, which we don't want since the user already has Tor and XMRig on their system, and allowing Feather to start Tor might conflict with the system Tor already running.

**Comment by telans** [comment]
> I think that this would embed it into the executable

I thought this would be a plus for ease of use, but yeah thinking on it it definitely seems a little redundant if the binaries aren't being shared.

**Comment by 00-matt** [comment]
We could patch the sources so that `-DXMRIG=/path/to/xmrig` simply sets the default of the textbox instead of embedding into the executable. Although I'm not sure which one it would pick, if the user had both `xmrig` and `xmrig-mo` installed. It doesn't seem worthwhile to create something like `eselect xmrig set ...`.
